name: Pytest with mkl

on:
  push:
    branches-ignore:
    - publish-gh-pages
    - master
    - rc

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2
    # Use conda-incubator/setup-miniconda for precise control of conda infrastructure
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        channels: conda-forge
        channel-priority: strict
        python-version: ${{ matrix.python-version }}
    - name: Install dependent packages
      run: |
        conda activate test
        conda install --yes python=${{ matrix.python-version }}
        #conda install --yes matplotlib-base pyyaml "libblas=*=*openblas" openblas h5py scipy pytest codecov pytest-cov spglib alm cmake c-compiler
        conda install --yes matplotlib-base pyyaml "libblas=*=*mkl" mkl-include h5py scipy pytest codecov pytest-cov spglib alm cmake c-compiler
    - name: Install phonopy
      run: |
        conda activate test
        git clone --depth 1 https://github.com/phonopy/phonopy.git
        cd phonopy
        pip install -e . -vvv
        cd ..
    - name: Install phono3py
      run: |
        conda activate test
        pip install -e . -vvv
    - name: Run pytest
      run: |
        pytest -v --cov=./ --cov-report=xml test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        verbose: true
